# To convert a list of numeric values into a one-dimensional NumPy aaray

In [1]:
# 216270307006
# odedra manshvi

import numpy as np

list=[1,2,3,4,5]
Array = np.array(list)
print(Array)

[1 2 3 4 5]


# to create a 3x3 matrix with values ranging from 2 to 10
 

In [2]:
# 216270307006
# odedra manshvi

import numpy as np

values =np.arange(2,11)
matrix=values.reshape(3,3)
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# to append values at the end of an array


In [3]:
# 216270307006
# odedra manshvi 

import numpy as np

arr = np.array([10, 20, 30])
print('Original Array : ', arr)

arr = np.append(arr, [40])
print('Array after appending : ', arr)

Original Array :  [10 20 30]
Array after appending :  [10 20 30 40]


# to create another shape from an array without changing its data(3*2 to 2*3)

In [4]:
# 216270307006
# odedra manshvi 

import numpy as np

x = np.array([10, 20, 30, 40, 50, 60])
y = np.reshape(x, (3, 2))

print("Reshape 3x2 :")
print(y)

z = np.reshape(x, (2, 3))
print("Reshape 2x3 :")
print(z)

Reshape 3x2 :
[[10 20]
 [30 40]
 [50 60]]
Reshape 2x3 :
[[10 20 30]
 [40 50 60]]
